spring.application.name=anzenfs

spring.threads.virtual.enabled=true

# Max size for a single file
spring.servlet.multipart.max-file-size=100GB

# Max size for the entire request
spring.servlet.multipart.max-request-size=10000GB

# Threshold after which files are written to disk instead of kept in memory
spring.servlet.multipart.file-size-threshold=10KB

# Increase max header size for huge multipart requests
server.max-http-header-size=10MB

