spring.application.name=anzenfs

spring.threads.virtual.enabled=true

# Keep these as they control the Tomcat connector itself, 
# not just the Spring Multipart resolver.
server.tomcat.max-swallow-size=-1
server.tomcat.max-post-size=-1
server.tomcat.max-parameter-count=20000
server.max-http-header-size=10MB

# Keep this to delay parsing until the controller is reached
spring.servlet.multipart.resolve-lazily=true
spring.servlet.multipart.max-file-size=128MB
spring.servlet.multipart.max-request-size=128MB

